- sentry-android-core/src/main/AndroidManifest.xml
Won't require user configuration in their app to add the permissions required by Sentry's SDK.
> feat: Require internet permission

- sentry-android-core/build.gradle.kts
- sentry-android-core/src/main/java/io/sentry/android/core/SentryInitProvider.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
- sentry-android/build.gradle.kts
libs don't need to generate BuildConfig and lints check don't need to run over Release type as well every time.
Speed up the build.
It doesn't generate the useless BuildConfig for libs.
Debugging and changing the unit tests to not use BuildConfig.
> No need to generate BuildConfig for libs

- sentry-android-core/build.gradle.kts
- sentry-android-core/proguard-rules.pro
- sentry-android-core/src/main/AndroidManifest.xml
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
- sentry-sample/build.gradle.kts
- sentry-sample/src/main/AndroidManifest.xml
Added the option via Manifest conf. to disable the auto-init of the Sentry SDK, so before fully initing the SDK we check this flag and don't do anything, the user may init. using a custom Application class.
the user may want to init. the SDK by code and pass custom parameters based on buildType/flavors and so on.
Mocking the manifest value and unit testing.
This should be written in the setup documentation
> opt in and out to auto-init SDK

- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
it fixes a broken test.
the test was making use of BuildConfig which was removed by another PR.
caused by the combination of 2 PRs
https://github.com/getsentry/sentry-android/pull/30
https://github.com/getsentry/sentry-android/pull/31
being sure that all the tests and build were green
> fixed broken test using BuildConfig

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryInitProvider.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
Sentry.init(...) will be called only if auto-init is enabled
We check if auto-init is enabled inside of the Sentry.init(...) method, this should be done even before calling it.
> Reading auto-init even before calling Sentry.init(...)

- sentry-core/src/main/java/io/sentry/core/AsyncConnectionFactory.java
Certificate should be validated by default. We can optionally expose that flag via `SentryOptions` for self-hosted Sentry on `https` with self-signed certs.
> ref: Don't bypass certo validation by defau;t

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryInitProvider.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
Overload to avoid instantiating `AndroidLogger` twice on a happy path
> ref: Reuse logger instance if possible

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidSerializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/TimeZoneDeserializerAdapter.java
- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/main/java/io/sentry/core/protocol/App.java
- sentry-core/src/main/java/io/sentry/core/protocol/Browser.java
- sentry-core/src/main/java/io/sentry/core/protocol/Device.java
- sentry-core/src/main/java/io/sentry/core/protocol/Gpu.java
- sentry-core/src/main/java/io/sentry/core/protocol/Mechanism.java
- sentry-core/src/main/java/io/sentry/core/protocol/Message.java
- sentry-core/src/main/java/io/sentry/core/protocol/OperatingSystem.java
- sentry-core/src/main/java/io/sentry/core/protocol/Package.java
- sentry-core/src/main/java/io/sentry/core/protocol/Request.java
- sentry-core/src/main/java/io/sentry/core/protocol/Runtime.java
- sentry-core/src/main/java/io/sentry/core/protocol/SdkVersion.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryException.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryStackFrame.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryStackTrace.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryThread.java
- sentry-core/src/main/java/io/sentry/core/protocol/User.java
added the unknown field to all the objects of the protocol
if the protocol is extended and all the SDKs are not synced, this will still send the properties over.
in the future get rid of IUnknownPropertiesConsumer if we decide to do our own json parser or stick to Gson
> added the unknown field to all the objects

- sentry-core/src/main/java/io/sentry/core/DateUtils.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/test/java/io/sentry/core/SentryEventTest.kt
- sentry-sample/src/main/AndroidManifest.xml
make timestamp in UTC
timestamp was not in UTC
> fix sentry UTC timestamp

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
added sentry cache dir folder to sentry options
NDK needs this path to create envelopes
unit test
> added cacheDirPath to SentryOptions

- sentry-core/src/main/java/io/sentry/core/DiagnosticLogger.java
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/Integration.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandler.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryOptionsTest.kt
- sentry-core/src/test/java/io/sentry/core/UncaughtExceptionHandlerIntegrationTest.kt
SentryOptions exposes `Integrations`.
A default integration is added to capture uncaught exceptions.
Basic sentry SDK feature
Unit tests
We could attemp unregisters but from what I recall when _unified API_ started @mitsuhiko was strongly against it.
If another integration also called `Thread.setDefaultUncaughtExceptionHandler` after we did, it wouldn't be possible to unregister, so that was the reason not to _pretend_ that we can unregister, even if best effort, and simply say: Once enabled, it's there for the lifetime of the app.
> feat: Uncaught exception is captured

- .appveyor.yml
- .travis.yml
installing build tools 29.x
because we are installing build tools 28.x but using 29.x
> WIP - fix tools version

- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
Callback executed before adding a breadcrumb to the scope.
Docs: https://docs.sentry.io/error-reporting/configuration/?platform=csharp#before-breadcrumb
> feat: BeforeBreadcrumb

- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/main/java/io/sentry/core/protocol/Request.java
- sentry-core/src/main/java/io/sentry/core/protocol/SdkVersion.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryStackFrame.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryStackTrace.java
- sentry-core/src/main/java/io/sentry/core/protocol/User.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
added the missing fields of the protocol.
there were a few missing fields
> added missing protocol fields

- sentry-core/src/main/java/io/sentry/core/protocol/SdkVersion.java
I suggest for now we just don't expose the internal structure.
Take `String name, String version` for packages and `String integration` and nothing else.
> ref: Don't expose getters for sdkVersion package/integration

- sentry-sample/src/main/java/io/sentry/sample/MainActivity.java
Adding strict mode to the sample.
We need to find out where we need to improve IO and violations.
> adding strict mode to app sample

- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-sample/src/main/AndroidManifest.xml
- sentry-sample/src/main/java/io/sentry/sample/MyApplication.java
added friendly Android init.
if auto-init is disabled, it's way more code to init. the SDK
> added Android friendly init.

- sentry-core/src/main/java/io/sentry/core/Hint.java
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/IHub.java
- sentry-core/src/main/java/io/sentry/core/NoOpHub.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
[Introducing `Hint` to callbacks](https://docs.sentry.io/error-reporting/configuration/?platform=csharp#before-breadcrumb).
> feat: Hint

- sentry-core/src/main/java/io/sentry/core/AsyncConnectionFactory.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/main/java/io/sentry/core/transport/Connection.java
- sentry-core/src/main/java/io/sentry/core/transport/CrashedEventStore.java
- sentry-core/src/test/java/io/sentry/core/transport/CrashedEventStoreTest.kt
Naming here not far from ideal.
We need to  discuss what a `Connection` is and a `Transport` is. Ideally in a separate PR. 
I suggest we get the behavior in, and refactor this since it'll involve changing the `AsyncConnection` and `HttpTransport`.
Follow up PR with a proposal will follow.
> feat: Uncaught event is persisted synchronously

- sentry-android-ndk/proguard-rules.pro
Only class used via reflection so far is `SentryNdk`.
The native layer isn't calling a anything via JNI. 
So the only rule we need **so far** is in this PR.
We need to review changes to `sentry-android-ndk` so that types used via reflection or JNI calls from native get added too.
> feat: Keep SentryNdk which is used via reflection

- sentry-core/src/main/java/io/sentry/core/AsyncConnectionFactory.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/main/java/io/sentry/core/cache/DiskCache.java
- sentry-core/src/main/java/io/sentry/core/cache/IEventCache.java
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/test/java/io/sentry/core/cache/DiskCacheTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/AsyncConnectionTest.kt
This adds the implementation of the `IEventCache` interface that stores the data to the filesystem.
Also it adds a simple ability of the `AsyncConnection` to store the events before attempting to send.
The implementation of the `DiskCache` is largely copied from `sentry-java`.
While a new config property governing the maximum of cached events is added in this PR, the user has no choice in selecting the implementation of the cache. Maybe this should be changed?
We need this to be able to persist the events before sending to enable crash/kill recovery.
Just unit tests, no testing on a real/simulated Android device
> Implementation of DiskCache and the ability to store events before sending

- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/main/java/io/sentry/core/protocol/App.java
- sentry-core/src/main/java/io/sentry/core/protocol/Device.java
- sentry-core/src/test/java/io/sentry/core/BreadcrumbTest.kt
added timestamp by default for breadcrumbs
timestamp was missing for breadcrumbs
unit tests
> missing timestamp for breadcrumbs

- sentry-core/src/main/java/io/sentry/core/protocol/SentryStackFrame.java
setting correct names to package and native attributes (stack frames)
package and native are reserved words in java, but we need them like this when serialized/deserialized.
getters and setters have the correct name, I will write an adapter later on, but let's fix it like this for now because it won't be a breaking change.
> setting correct names to package and native attributes (stack frames)

- sentry-core/src/main/java/io/sentry/core/SendCachedEvent.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
I'd like to revert this with the following reasoning.
Hing is `Object`. So if simply using the base type on the right hand side of the assignment to make the compiler happy, we could do:
`Object hint = new SendCachedEventHint()`;
I'm sure we agree not to do this since it doesn't express the intent here. I'm instantiating `SendCachedEventHint` but can it be replaced by any `Object`?
This isnt' the same with `var` since in this case it would be, I don't care what the compiler infers. I see you're instantiating `SendCachedEventHint` and that means that's important and can't be overlooked.
`SendCachedEventHint` implements two interfaces and so far (up for discussion to change if there's a better way) a `hint is any Object` where the SDK support some well-known types (so far the 3 interfaces …
> ref: revert type assignment

- sentry-core/src/main/java/io/sentry/core/SentryStackTraceFactory.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/test/java/io/sentry/core/SentryStackTraceFactoryTest.kt
Since we add the app's namespace as `inAppInclude`, I propose default all frames as InApp=false.
Sentry should anyway show the whole stacktrace if *all frames* are inApp=false so if we somehow missed it, it would show the whole thing.
The default should be good enough as in only showing the app's stack frames and hiding everything else. If no app frames are included, everything is shown.
> feat: Unknown frames are not in app

- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
No frame was marked as inApp because inAppInclude list was null and passed as an argument to the factory before the Android package could add (first the instance of the list) the inApp frames
> fix: inapp

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
check the existence of sentry metadata before blowing up an exception
if the file didn't exist, it was causing FileNotFoundException and some noisy in the logs
> check the existence of sentry metadata before blowing up an exception

- sentry-android-core/proguard-rules.pro
- sentry-android-ndk/proguard-rules.pro
added more exceptions to proguard
NDK cant be init. on release mode
move all classes to protocol package, so I dont need to do:
-keep class io.sentry.core.** { *; }
-keep class io.sentry.core.protocol.** { *; }
but only:
-keep class io.sentry.core.protocol.** { *; }
> fix proguard

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
listing assets file on the wrong dir (when looking up for sentry-debug-meta.properties)
sentry-debug-meta.properties was not being found even if it was there.
debugging with proguard enabled
> listing assets file on the wrong dir

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/IHub.java
- sentry-core/src/main/java/io/sentry/core/ISentryClient.java
- sentry-core/src/main/java/io/sentry/core/NoOpHub.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/NoOpSentryClientTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
add method to captureMessage with level
captureMessage didn't support level yet.
> add method to captureMessage with level

- sentry-android/src/main/AndroidManifest.xml
- sentry-sample/src/main/AndroidManifest.xml
benefiting of manifest merging when minSdk < 21
if you wanna support NDK >= 21 but also to support Android SDK < 21, you need to set this merging strategy.
```
<uses-sdk
tools:overrideLibrary="io.sentry.android, io.sentry.android.ndk"/>
```
with this PR, you just need:
```
<uses-sdk
tools:overrideLibrary="io.sentry.android"/>
```
> benefiting of manifest merging when minSdk < 21

- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/test/java/io/sentry/core/ScopeTest.kt
execute beforeBreadcrumb also for scope
beforeBreadcrumb was not being executed when breadcrumbs were added directly to the scope
unit tests
refactor it, we have a design flaw here, I don't like the solution, but we need to have it done till tomorrow.
> execute beforeBreadcrumb also for scope

- sentry-android-core/proguard-rules.pro
See: https://github.com/getsentry/sentry/pull/15795
Once merged/deployed, sentry.io would not longer require exception types not to be minified.
> ref: Don't avoid exception type minification

- buildSrc/src/main/java/Config.kt
- sentry-android-core/proguard-rules.pro
- sentry-android-core/src/main/java/io/sentry/android/core/UnknownPropertiesTypeAdapterFactory.java
make gson retro compatible with older versions of AGP
when compiling a project and using the latest version of sentry-android, an error was happening due to:
https://github.com/google/gson/issues/1597
investigation due to:
https://github.com/getsentry/sentry-android/issues/171
compiling a sample project with all the AGP versions >= 3 till the latest one.
find a way to compile a sample project with all AGP versions, to be sure that we don't release something which is breaking the build for older versions.
> fix desugaring Gson/AGP

- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/IHub.java
- sentry-core/src/main/java/io/sentry/core/NoOpHub.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/main/java/io/sentry/core/cache/DiskCache.java
- sentry-core/src/main/java/io/sentry/core/transport/NoOpEventCache.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/ScopeTest.kt
adding scope methods to sentry static class
making migration easier, otherwise one will need to call `Sentry.configureScope(...)`
I'll do unit tests
> adding scope methods to sentry static class

- sentry-android-ndk/src/main/jni/sentry.c
- sentry-sample/CMakeLists.txt
- sentry-sample/build.gradle.kts
- sentry-sample/src/main/cpp/native-sample.cpp
- sentry-sample/src/main/java/io/sentry/sample/MainActivity.java
- sentry-sample/src/main/java/io/sentry/sample/NativeSample.java
linking sentry-native directly to be able to debug it.
it was not possible to debug sentry-native if not defining methods in sentry.c.
debugging it.
> linking sentry-native directly to be able to debug it

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/Installation.java
generating android_id if Settings.Secure.ANDROID_ID is buggy or non existent.
https://android-developers.googleblog.com/2011/03/identifying-app-installations.html
debugging all the cases, this class has not been tested yet (unit tests), will do it later on.
> workaround android_id

- sentry-core/src/main/java/io/sentry/core/SentryThreadFactory.java
- sentry-core/src/test/java/io/sentry/core/SentryThreadFactoryTest.kt
fix Android bug on API 24 and 25 about threads/stack traces.
https://issuetracker.google.com/issues/64122757
if not fixed, threads and stack traces will be incompleted.
unit tests.
> fix Android bug on API 24 and 25 about threads/stacktraces

- sentry-core/src/main/java/io/sentry/core/IHub.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
Common use case is: `Sentry.addBreadcrumb("bla");`
Or, also used for the guide: `Sentry.addBreadcrumb(activity.getComponentName().flattenToShortString() + "started", "activity");`
> feat: addBreadcrumb overloads

- MIGRATION.md
creating migration guide markdown
people need to know how to migrate from 1.x to 2.x version.
> migration guide markdown

- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
- sentry-core/src/main/java/io/sentry/core/Sentry.java
throw an exception if DSN is not set.
if DSN is not set, user needs to know right away, it might be a misconfiguration.
> throw an exception if DSN is not set

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/assets/sentry-debug-meta.properties
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
added executor for caching values out of the main thread.
right now every capture exception or message will do IO on the main thread and data is static, so it may be cached.
executing and StrictMode.
> added executor for caching values out of the main thread

- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/test/java/io/sentry/core/MainEventProcessorTest.kt
dist may be set on options.
dist should be possible to be set on options as well.
unit tests.
> dist may be set on options

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransportGate.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/util/CheckConnectivity.java
- sentry-android-core/src/main/java/io/sentry/android/core/util/ConnectivityChecker.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-core/src/main/java/io/sentry/core/AsyncConnectionFactory.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
added an android transport gate to check if the device is online or not, so the event only will try to send if it actually has a connected network.
check if the device has a connected network before trying to send the event, right now even if it's not connected anywhere, we are trying to send, so wasting resources.
unit tests on the setup, but it's hard to mock the whole network conf. of the android framework.
> added android transport gate

- sentry-android-core/src/test/java/io/sentry/android/core/EnvelopeFileObserverIntegrationTest.kt
- sentry-core/src/test/java/io/sentry/core/EnvelopeSenderTest.kt
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
- sentry-core/src/test/java/io/sentry/core/UncaughtExceptionHandlerIntegrationTest.kt
In some parts of the unit tests `Mockito.verify(something, times(1)).someMethod()` is used. This can be simplified to `Mockito.verify(something).someMethod()`.
It makes the code simpler and less verbose.
By running the tests.
None.
> Remove redundant times(1) for Mockito.verify

- sentry-core/src/main/java/io/sentry/core/Dsn.java
- sentry-core/src/test/java/io/sentry/core/DsnTest.kt
The code coverage for `Dns` is raised to 100% with this PR.
It is better to have a higher code coverage to be able to change code later. Furthermore, one TODO is removed.
With unit tests.
None.
> Raise code coverage for Dsn to 100%

- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/test/java/io/sentry/core/CustomEventProcessor.kt
- sentry-core/src/test/java/io/sentry/core/ScopeTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
added event processors to scope
the current scope doesn't support event processors, but it's part of the unified API.
unit tests.
> added event processors to scope

- sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/EnvelopeFileObserverIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/AnrIntegrationTest.kt
- sentry-core/src/main/java/io/sentry/core/DirectoryProcessor.java
- sentry-core/src/main/java/io/sentry/core/cache/DiskCache.java
written unit tests for ANR integration.
there were no unit tests for ANR integration.
> written unit tests to ANR integration

- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/main/java/io/sentry/core/transport/IBackOffIntervalStrategy.java
fix lgtm alerts.
integrate https://lgtm.com/projects/g/getsentry/sentry-android
> fix lgtm alerts

- sentry-native-sample/src/main/java/io/sentry/nativesample/MainActivity.java
enable timber on native sample
timber was not enabled.
> enable timber on native sample

- sentry-core/src/main/java/io/sentry/core/IHub.java
- sentry-core/src/main/java/io/sentry/core/ISentryClient.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
added a few java docs.
we are poor of javadocs.
more and more javadocs
> added a few java docs (Sentry, Hub and SentryClient)

- sentry-core/src/main/java/io/sentry/core/SentryExceptionFactory.java
- sentry-core/src/main/java/io/sentry/core/SentryStackTraceFactory.java
- sentry-core/src/main/java/io/sentry/core/SentryThreadFactory.java
- sentry-core/src/test/java/io/sentry/core/SentryExceptionFactoryTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryStackTraceFactoryTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryThreadFactoryTest.kt
do not set frames if there's none.
fix https://github.com/getsentry/sentry-android/issues/233
unit test.
> do not set frames if there's none

- sentry-core/src/main/java/io/sentry/core/Dsn.java
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/test/java/io/sentry/core/transport/HttpTransportTest.kt
few improvements identified by a pre-release list.
to meet the unified API.
> few improvements identified by a pre-release list

- sentry-core/src/test/java/io/sentry/core/SentryValuesTest.kt
Add tests for `SentryValues` to raise its code coverage to 100%.
Easier to change `SentryValues`.
With running the unit tests.
> Add tests for SentryValues

- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/test/java/io/sentry/core/ScopeTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
- sentry-native-sample/build.gradle.kts
- sentry-sample/src/main/java/io/sentry/sample/MainActivity.java
refactoring breadcrumbs callback.
callbacks were called on Hub and Scope, but could it be placed and logged together.
executing it, there is unit tests already.
> refactoring breadcrumbs callback

- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryInitProvider.java
- sentry-core/src/main/java/io/sentry/core/DiagnosticLogger.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
Javadocs for SentryOptions.
Users may learn directly from code.
> Javadocs for SentryOptions

- sentry-android-core/src/test/java/io/sentry/android/core/EnvelopeFileObserverIntegrationTest.kt
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/HubAdapter.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/UncaughtExceptionHandlerIntegrationTest.kt
https://github.com/getsentry/sentry-android/pull/245 was deferred, but we need this change.
> Added HubAdapter to call Sentry static methods from Integrations

- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
A Hub per Thread makes sense in server applications.
That's not the case for Mobile or desktop apps. Where it's a single 'user session' for the whole process, UI thread is scarce resource and lots of work are queued to worker threads.
This PR introduces a flag to control the behavior of the `Sentry` static class. By default, it'll continue to clone the `mainHub` per thread. If the flag is flipped (which happens in the Android SDK), a single Hub (and its scope) is shared. Meaning the breadcrumbs added in the UI thread as well as worker threads making HTTP requests also end up on outgoing events.
> feat: Hub mode configurable

- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
moving back ANR timeout from long to int param..
as a long, it was gonna require that users set value with an "l" or "L" at the end, like 1000l, and might cause a lot of noise to us on support, so a normal int would be fine and we convert it to long.
how it is:
`<meta-data android:name="io.sentry.anr.timeout-interval-mills" android:value="1000l" />`
how it's gonna be:
`<meta-data android:name="io.sentry.anr.timeout-interval-mills" android:value="1000" />`
ran unit tests.
> moving back ANR timeout from long to int param.

- .travis.yml
- sentry-android-ndk/build.gradle.kts
- sentry-native-sample/build.gradle.kts
- sentry-sample/build.gradle.kts
build all ABIs.
API env. It only makes sense if we have integration tests and emulators, so we actually create emulators based on the APIs (matrix).
ABI env. is the same case, we could speed up builds for specific emulator architectures, but we don't have it now, we can rollback it later when we actually do it.
Another thing is, we want to download the artifacts and CI right now is compiling to specific ABIs, so we could add a new one for all the ABIs or remove them all as I do now, because there's no meaning right now.
let's check CI right now.
> build all ABIs

- sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/EnvelopeFileObserverIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java
- sentry-core/src/main/java/io/sentry/core/Integration.java
- sentry-core/src/main/java/io/sentry/core/SendCachedEventFireAndForgetIntegration.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
make integrations public.
When a user wants to remove an integration, it would be possible doing:
options.getIntegrations() iterating it and comparing instances, but integrations are not public, yet.
CI
> make integrations public

- sentry-native-sample/src/main/java/io/sentry/nativesample/MainActivity.java
- sentry-sample/src/main/java/io/sentry/sample/MyApplication.java
fix strictMode typo.
just fixing a typo.
> fix strictMode typo

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
fixes #259 - NPE check on getExternalFilesDirs items.
https://developer.android.com/reference/android/content/Context.html#getExternalFilesDirs(java.lang.String)
> the absolute paths to application-specific directories. Some individual paths may be null if that shared storage is not currently available. The first path returned is the same as getExternalFilesDir(java.lang.String).
Ran on Nexus 5X API 21 emulator.
> fixes #259 - NPE check on getExternalFilesDirs items.

- sentry-android-core/src/main/java/io/sentry/android/core/adapters/DateDeserializerAdapter.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidSerializerTest.kt
- sentry-core/src/main/java/io/sentry/core/DateUtils.java
Support mills timestamp format.
eg 1581410911.988
which is {seconds}.{mills}
JS sends mills timestamp format and we need to support hybrid SDKs.
unit test.
> Support mills timestamp format

- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
read release conf. on manifest.
one would be able to set a custom release in the manifest and no only in the code.
> read release conf. on manifest

- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/main/java/io/sentry/core/SentryThreadFactory.java
- sentry-core/src/test/java/io/sentry/core/MainEventProcessorTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryThreadFactoryTest.kt
feat: attach stacktraces
attach stacktraces is disabled by default, but it should have a flag to opt-in.
right now is enabled by default and there's no opt-out.
unit test.
> feat: attach threads/stacktraces

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
fix android lint warning.
if using `buildToolsVersion = "30.0.0-rc1"` project won't compile due new linting.
building it.
> fix android lint warning

- sentry-core/src/main/java/io/sentry/core/SentryExceptionFactory.java
- sentry-core/src/test/java/io/sentry/core/SentryExceptionFactoryTest.kt
set current threadId when theres no mechanism to rely on.
exception had no threadId if it was not a exception mechanism and this makes the thread selector not happy on the dashboard.
unit test and debugging it.
> set current threadId when theres no mechanism to rely on

- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/test/java/io/sentry/core/MainEventProcessorTest.kt
This adds support for the default server name specified in sentry options so that it can be used in events.
This feature exists in `sentry-java` and is a documented Sentry option, e.g. https://docs.sentry.io/error-reporting/configuration/?platform=csharp#server-name
Updated the unit tests of the `MainEventProcessor` to test that the option is applied.
> Add the default serverName to SentryOptions and use it in MainEventProcessor

- sentry-core/src/main/java/io/sentry/core/transport/StdoutTransport.java
- sentry-core/src/test/java/io/sentry/core/transport/StdoutTransportTest.kt
A common pattern is to "log" exceptions and messages to Sentry. It's a
convenient place to collect programmer errors: situations that
absolutely should not happen according to the business logic, but happen
anyway because of constraints not caught by the type system or test
suite.
In debug builds we often have Sentry disabled because we don't want to
clutter it with all the ANRs and simple mistakes of development life.
This can mean that exceptions we are "logging" to Sentry get missed.
Instead we can use a `StdoutTransport`, logging them to the stdout log:
```kotlin
SentryAndroid.init(this) { options ->
if (BuildConfig.DEBUG) {
options.setTransport(StdoutTransport(options.serializer))
}
}
```
This will log a message like so:
```
03-20 18:32:47.623 17385-17436/io.sentry.sample …
```
> Add a StdoutTransport

- sentry-core/src/main/java/io/sentry/core/AsyncConnectionFactory.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/cache/IEnvelopeCache.java
- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/main/java/io/sentry/core/transport/NoOpEnvelopeCache.java
- sentry-core/src/test/java/io/sentry/core/cache/SessionCacheTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/AsyncConnectionTest.kt
renaming session cache interface, implementation is still called SessionCache as it takes a SentryOptions and reads session path, etc...
following Open–closed principle
> renaming session cache interface

- sentry-android-core/src/test/java/io/sentry/android/core/LifecycleWatcherTest.kt
- sentry-core/src/main/java/io/sentry/core/EnvelopeReader.java
- sentry-core/src/main/java/io/sentry/core/EnvelopeSender.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelope.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeHeader.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeHeaderAdapter.java
- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
- sentry-core/src/test/java/io/sentry/core/SentryEnvelopeTest.kt
eventId on envelope's header should be nullable.
because an envelope only requires an eventId if there's an event and related items in it.
> eventId on envelope's header should be nullable

- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-sample/src/main/AndroidManifest.xml
session duration should be in seconds.
sequence was current timezone
duration was in millis.
sequence is UTC.
> session duration should be in seconds, sequence should be UTC

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransportGate.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransportGateTest.kt
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/main/java/io/sentry/core/transport/ITransportGate.java
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/AsyncConnectionTest.kt
renaming transport gate method
`isSendingAllowed()` seems to be related to our RetryAfter impl., but actually this checks wether if the device is online or not, so `isConnected` would be better.
> renaming transport gate method

- sentry-core/src/main/java/io/sentry/core/EnvelopeSender.java
- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/main/java/io/sentry/core/util/CollectionUtils.java
- sentry-core/src/test/java/io/sentry/core/cache/SessionCacheTest.kt
logging envelopes path when possible instead of nullable id
envelopes that don't have an `id` would log as `null` which is not useful at all.
running it.
> logging envelopes path when possible instead of nullable id

- sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/AnrIntegrationTest.kt
fix racey ANR integration.
if different threads add an AnrIntegration and close it, it can be racey as there's a global static field.
ran unit tests and debugging it
> fix racey ANR integration

- sentry-core/src/main/java/io/sentry/core/Sentry.java
Avoiding the extraneous `ThreadLocal.get()` is quite easy in `currentHub()` so we
should not do it.
`currentHub()` is a hotspot method (at least within the context of Sentry) and `ThreadLocal.get()` involves a map lookup (the more thread locals there are in the current thread, the
more expensive that is and the number of thread locals in the current
thread is out of our control).
By thinking hard :smile:
> Avoid getting a threadlocal twice.

- sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java
avoid crash if NDK throws UnsatisfiedLinkError.
While this doesn't fix #341 it might help till we get there.
threw UnsatisfiedLinkError myself
consider https://github.com/KeepSafe/ReLinker as it's recommended in the Android official docs anyway.
> avoid crash if NDK throws UnsatisfiedLinkError

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-core/src/main/java/io/sentry/core/DirectoryProcessor.java
- sentry-core/src/main/java/io/sentry/core/SendCachedEventFireAndForgetIntegration.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
change integration order for cached outbox events.
as sentry-native move files around on init. and the outbox file observer now is inited after the NDK integration.
This integration also should be executed afterwards, so hard crashes will be in place and ready to be sent.
I've needed to make DirectoryProcessor public.
running and testing it.
> change integration order for cached outbox events

- sentry-core/src/main/java/io/sentry/core/Dsn.java
- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/test/java/io/sentry/core/DsnTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/HttpTransportTest.kt
envelope has a dedicated endpoint.
@jan-auer can tell more about it.
fixed and ran unit tests.
> envelope has dedicated endpoint

- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
- sentry-core/src/test/java/io/sentry/core/SessionTest.kt
a session should be ended with an exited state.
the session was being ended always with abnormal if errorCount was > 0.
if there's an open session that should not be there and there's no ndk marker file, then it should be abnormal.
unit test
> session should be exited state if state is ok

- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
if there's a leftover session file and its crashed, we should not overwrite its state
if you are killing the app all the time via IDE or even changing the normal shutdown of the App, it might happen that a session is crashed and not sent yet, on App. restart, it's gonna be marked as abnormal, but it shouldn't if it's crashed, we should trust that file and send it as it is.
> if theres a left over session file and its crashed, we should not overwrite its state

- sentry-android-core/src/main/java/io/sentry/android/core/SessionTrackingIntegration.java
- sentry-sample/build.gradle.kts
check for androidx availability on runtime
if you don't want to use the release health feature, you actually can exclude it.
just to avoid an error if you have enabled it and can't use androidx, we check on runtime via reflection.
running it/build.
> check for androidx availability on runtime

- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
update current session on session start after deleting the previous session.
when starting a new session, if there's a leftover session, we end it and start a new one, even in this case, we should flush the new session to the current session file.
> update current session on session start after deleting previous session

- sentry-android-core/src/main/java/io/sentry/android/core/util/ConnectivityChecker.java
fix the wrong check for cellular network capability
when the device was connected thru a cellular network, the connection type was null
running it
> fix wrong check for cellular network capability

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
check external storage size even if its read only
if external storage size was read-only, it was not able to get external storage stats
running it
> check external storage size even if its read only

- sentry-core/src/main/java/io/sentry/core/SentryExceptionFactory.java
- sentry-core/src/test/java/io/sentry/core/SentryExceptionFactoryTest.kt
exceptions should be sorted oldest to newest
Fix #363
Probably related to getsentry/sentry/pull/18227
running and unit testing
> exceptions should be sorted oldest to newest

- sentry-android-ndk/CMakeLists.txt
- sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java
- sentry-android-ndk/src/main/jni/sentry.c
- sentry-sample/CMakeLists.txt
- sentry-sample/src/main/java/io/sentry/sample/NativeSample.java
This loads all the non-essential-system libraries explicitly in order, to hopefully avoid dynamic linker errors such as #341
> fix: Merge loadLibrary calls for sentry-native and clean up CMake files

- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
In AsyncConnection.send the variable for IEnvelopeCache was named currentEventCache.
It was renamed to currentEnvelopeCache.
Makes the code easier to read.
Unit test still pass.
None
> ref: Rename currentEventCache to currentEnvelopeCache

- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-core/src/main/java/io/sentry/core/protocol/Device.java
add ScheduledForRemoval annotation to deprecated methods
so we can remove them on the next major bump.
> add ScheduledForRemoval annotation to deprecated methods

- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/test/java/io/sentry/core/transport/HttpTransportTest.kt
if retry after header has empty categories, apply retry after to all of them.
the current implementation was not handling empty categories.
> if retry after header has empty categories, apply retry after to all of them

- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/test/java/io/sentry/core/UncaughtExceptionHandlerIntegrationTest.kt
- sentry-sample/src/main/AndroidManifest.xml
> feat: Options for uncaught exception and make SentryOptions list Thread-Safe

- .appveyor.yml
- .travis.yml
- sentry-android-ndk/build.gradle.kts
> BUMP NDK to latest stable version 21.1.6352462

- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-sample/src/main/AndroidManifest.xml
- sentry-sample/src/main/java/io/sentry/sample/MainActivity.java
make ANR 5s by default
ANR is very spammy sometimes and originally this was 5s by default.
> make ANR 5s by default

- sentry-android-core/src/main/java/io/sentry/android/core/PhoneStateBreadcrumbsIntegration.java
fix when PhoneStateListener is not ready for use
probably because `Looper.myLooper()` returns null, but I can't find out how
java.lang.RuntimeException: Unable to create application package_here: java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
at android.app.ActivityThread.access$1300(ActivityThread.java:219)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at …
> fix when PhoneStateListener is not ready for use

- sentry-core/src/main/java/io/sentry/core/transport/CurrentDateProvider.java
- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/main/java/io/sentry/core/transport/ICurrentDateProvider.java
- sentry-core/src/test/java/io/sentry/core/transport/HttpTransportTest.kt
add a DateTimeProvider for making retry after testable
we were using Thread.sleep(x) and this was slowing down the tests and could also become flakey, with this we can assert things properly.
thanks @philipphofmann for the code review #381 good catch.
unit tests.
> add a DateTimeProvider for making retry after testable

- buildSrc/src/main/java/Config.kt
- sentry-android-core/build.gradle.kts
- sentry-android-core/src/main/java/io/sentry/android/core/LifecycleWatcher.java
- sentry-android-core/src/test/java/io/sentry/android/core/LifecycleWatcherTest.kt
- sentry-core/src/main/java/io/sentry/core/transport/CurrentDateProvider.java
- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/main/java/io/sentry/core/transport/ICurrentDateProvider.java
removed Thread.sleep from LifecycleWatcher tests, using awaitility and DateProvider
Thread sleep was slowing down tests and also tests using `currentTimeMillis` were not deterministic.
`@Ignore` test should be working now
> removed Thread.sleep from LifecycleWatcher tests, using awaitility and DateProvider

- sentry-android-core/src/main/java/io/sentry/android/core/SystemEventsBreadcrumbsIntegration.java
enha: only set breadcrumb extras if not empty
sending empty extras is non sense
> enha: only set breadcrumb extras if not empty

- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
added missing getters on Breadcrumb and SentryEvent
it was not possible to use `beforeSend` or `beforeBreadcrumb` with those fields.
> added missing getters on Breadcrumb and SentryEvent

- sentry-android-core/src/main/java/io/sentry/android/core/TempSensorBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/TempSensorBreadcrumbsIntegrationTest.kt
do not add automatic and empty sensor breadcrumbs
inspired by #400
ran it
find out how to avoid `@Ignore` test, tried mocking, reflection, hacking private-package but still `SensorEvent.values` is always null, maybe because of `UnsupportedAppUsage` in the ctor.
> do not add automatic and empty sensor breadcrumbs

- sentry-android-ndk/src/main/jni/sentry.c
set missing release, environment and dist to sentry-native options
those fields were missing on NDK hard crashes and the Android bits were not overwriting it as the app could be upgraded before restarting it.
ran sample.
> fix: set missing release, environment and dist to sentry-native options

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegrationTest.kt
fix: initing SDK on AttachBaseContext
Similar issue getsentry/sentry-java/pull/714
Fix #408
> fix: initing SDK on AttachBaseContext

- sentry-android-core/src/main/java/io/sentry/android/core/ANRWatchDog.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/ANRWatchDogTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AnrIntegrationTest.kt
fix: before raising ANR event, we check ProcessErrorStateInfo if available
ANR events are too noisy
#406
> fix: before raising ANR event, we check ProcessErrorStateInfo if available

- sentry-android-core/src/main/java/io/sentry/android/core/PhoneStateBreadcrumbsIntegration.java
fix: Phone state breadcrumbs require read_phone_state on older OS versions
Fix: #413
running API 14 and 16
> fix: Phone state breadcrumbs require read_phone_state on older OS versions

- gradle/wrapper/gradle-wrapper.properties
downgrade Gradle to 6.4
appveyor is having hard times with newest Gradle version.
org.gradle.api.internal.classpath.UnknownModuleException: Cannot locate JAR for module 'ant' in classpath: [C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-launcher-6.4.1.jar, C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-bootstrap-6.4.1.jar, C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-base-services-6.4.1.jar, C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\lib\gradle-core-api-6.4.1.jar, C:\Users\appveyor\.gradle\wrapper\dists\gradle-6.4.1-all\13imxtezgn9nwzqt8rgtkunh1\gradle-6.4.1\ …
> downgrade Gradle to 6.4

- sentry-core/src/main/java/io/sentry/core/Session.java
fix: add Abnormal to the Session.State enum as its part of the protocol
this would make the current version be compatible with older generated sessions data.
but it's not currently being used by the SDK.
> fix: add Abnormal to the Session.State enum as its part of the protocol

- sentry-core/src/main/java/io/sentry/core/NoOpLogger.java
make NoOpLogger public
```
SentryAndroid.init(applicationContext) { options ->
options.setLogger(null)
}
```
Still logs a few thing that runs before the OptionsConfiguration.configure.
one may need to `SentryAndroid.init(context, NoOpLogger.getInstance())` if they want a total radio silence.
The other way would be to implement `ILogger` on its own that does nothing aka NoOp.
> fix: make NoOpLogger public

- sentry-android-core/src/test/java/io/sentry/android/core/EnvelopeFileObserverIntegrationTest.kt
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/UncaughtExceptionHandlerIntegrationTest.kt
fix: Sentry.init register integrations after creating main Hub instead of in the main Hub ctor
when integrations are registered on Hub ctor and async integrations are fired,
it might and actually happened that integrations called captureSomething
and hub was still NoOp.
Registering integrations here make sure that Hub is already created.
Find a proper way of registering global and only once integrations.
> fix: Sentry.init register integrations after creating main Hub instead of in the main Hub ctor

- sentry-android-core/src/main/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegrationTest.kt
fix: filter trim memory breadcrumbs
no need to add breadcrumbs for memory warnings that are not so important, yet.
> fix: filter trim memory breadcrumbs

- sentry-android-core/src/main/java/io/sentry/android/core/BuildInfoProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/IBuildInfoProvider.java
- sentry-android-core/src/main/java/io/sentry/android/core/util/RootChecker.java
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/util/RootCheckerTest.kt
make root checker better and minimize false positive.
I still could reproduce false positive on the current root checker
> enha: make root checker better and minimize false positive

- buildSrc/src/main/java/Config.kt
> bump awaitility to 4.0.3

- sentry-android-core/src/main/java/io/sentry/android/core/LifecycleWatcher.java
fix: update last session timestamp
when app goes to foreground and get lastUpdatedSession, it should do the same on when app goes to background, so app won't stop and start sessions every time after the interval period.
running it
> fix: update last session timestamp

- gradle.properties
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
fix: do not lookup sentry-debug-meta but instead loads it directly
probably fixes #442
one may have thousands of asset files and this will slow down the startup time.
instead of looking up if the sentry-debug-meta exists, we try to load it directly and take care of `FileNotFoundException`.
the downside is: if one doesn't have asset files, catching the exception might be more expensive than the looking up itself, but worth it.
running it, tests are in place.
ideally `sentry-debug-meta.properties` will be a manifest config or SentryOptions, as a file this is suboptimal, but needed because of retro compatibility.
> fix: do not lookup sentry-debug-meta but instead load it directly

- sentry-sample/src/main/AndroidManifest.xml
extra recommended permission, we'd be able to collect device ringing breadcrumbs (PhoneStateBreadcrumbsIntegration)
so people are aware of it, older Android versions require this permission.
> add READ_PHONE_STATE permission on the sample app.

- sentry-android-core/src/test/java/io/sentry/android/core/AndroidSerializerTest.kt
- sentry-core/src/main/java/io/sentry/core/DateUtils.java
fix: timestamp with millis from react-native should be already in UTC format
timestamps were off in react-native events if not UTC.
unit test.
release a new sentry-react-native version.
> fix: timestamp with millis from react-native should be in UTC format

- sentry-core/build.gradle.kts
IDEA’s gradle support failed to inherit language/bytecode level from
parent project, causing mockito failures w/ 11 bytecode.
Explicitly set Java / JVM versions for the `sentry-core` subproject.
Technically it doesn’t fix a Sentry bug but rather papers over a bug in IDEA 2020.1.2 which makes tests fail from the IDE: It doesn’t detect the source & target JVM versions from the parent project. Then it generates JVM 11 bytecode, which our Mockito can’t handle.
Reimported in IDEA 2020.1.2 and saw that the JVM versions were now correct in the settings & the tests were green.
Had some tests that did not seem to deliver any result (green or red) in AS 4.0 but this did not change after reverting this change locally so it’s at least unrelated.
> Make JVM target explicit in sentry-core

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/ILoadClass.java
- sentry-android-core/src/main/java/io/sentry/android/core/LoadClass.java
- sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ContextUtilsTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/NdkIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryNdk.kt
fix: init native libs if available on sdk init
one could init the SDK with an empty DSN and still load a native lib that depends on the libsentry, the libsentry was never initialized, now it is and it'll be NoOp as the Android SDK.
running on API 16 and 28, with and without an empty DSN.
> fix: init native libs if available on sdk init

- sentry-android-core/src/test/java/io/sentry/android/core/AndroidSerializerTest.kt
- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-core/src/test/java/io/sentry/core/SessionTest.kt
fix: negative session sequence if the date is before java date epoch
often old emulators may have a date not set, which means it'll be January 1, 1970, 00:00:00 GMT
when converting timezones to UTC, it may give a wrong date, which should be offset to not be negative.
> fix: negative session sequence if the date is before java date epoch

- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-core/src/test/java/io/sentry/core/ScopeTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
- sentry-core/src/test/java/io/sentry/core/SessionTest.kt
fix: clone session before sending to the transport
if a session was mutated before sent and discarded, fields could be wrong as they are mutable.
> fix: clone session before sending to the transport

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidSerializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/ContextsSerializerAdapter.java
- [X ] Bugfix
fix: contexts serializer avoids reflection and fixes desugaring issue
#476
running it, tests are already in place
> fix: contexts serializer avoids reflection and fixes desugaring issue

- sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt
- sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt
fix: Timber adds breadcrumb even if event level is < minEventLevel
Sentry was adding breadcrumbs only if minEventLevel was >= level
> fix: Timber adds breadcrumb even if event level is < minEventLevel

- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/test/java/io/sentry/core/transport/HttpTransportTest.kt
- sentry-sample/src/main/AndroidManifest.xml
feat: log request if response code is not 200
we were not logging the error response on every possibility.
running it, unit tests already exist.
> feat: log request if response code is not 200

- sentry-core/src/test/java/io/sentry/core/DiagnosticLoggerTest.kt
- sentry-core/src/test/java/io/sentry/core/SendCachedEventFireAndForgetIntegrationTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
ref: fix test linting
linting was complaining
> ref: fix test linting

- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryEventTest.kt
fix: event.level fatal is not a crashed session
only the mechanism.handled has the ability to end a session as crashed.
> fix: event.level fatal is not a crashed session

- sentry-core/src/main/java/io/sentry/core/SentryEnvelope.java
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/main/java/io/sentry/core/transport/ITransport.java
- sentry-core/src/main/java/io/sentry/core/transport/NoOpTransport.java
- sentry-core/src/main/java/io/sentry/core/transport/StdoutTransport.java
- sentry-core/src/main/java/io/sentry/core/transport/TransportResult.java
- sentry-core/src/test/java/io/sentry/core/transport/AsyncConnectionTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/HttpTransportTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/StdoutTransportTest.kt
feat: drop store endpoint in favor of envelope
relay first
> feat: drop store endpoint in favor of envelope

- build.gradle.kts
- sentry-android-core/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-timber/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-core/build.gradle.kts
fix: ktlint for kts files
kts files were not properly checked
> fix: ktlint for kts files

- sentry-core/src/main/java/io/sentry/core/cache/CacheStrategy.java
- sentry-core/src/main/java/io/sentry/core/cache/DiskCache.java
- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
- sentry-core/src/test/java/io/sentry/core/cache/CacheStrategyTest.kt
feat: rotate cache folder
if the cache folder is full, we don't cache them anymore, ideally, we'd delete the oldest files making room for the new ones
> feat: rotate cache folder

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-core/src/main/java/io/sentry/core/SendFireAndForgetEventSender.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/main/java/io/sentry/core/ShutdownHookIntegration.java
- sentry-core/src/test/java/io/sentry/core/SentryOptionsTest.kt
- sentry-core/src/test/java/io/sentry/core/ShutdownHookIntegrationTest.kt
- Call `Sentry#close` on JVM shutdown - as a result flush all Sentry events that are in progress.
- Configure `SendCachedEventFireAndForgetIntegration` by default only for Android as for the console/server application cache does not apply
Without this change, when Sentry is used in the console application, the main thread may finish before events are sent to Sentry and as a result no events are sent.
This idea was briefly discussed with @marandaneto and it's a subject for discussion - perhaps there is a better way to achieve the same result without attaching shutdown hook.
> Call `Sentry#close` on JVM shutdown.

- sentry-core/src/main/java/io/sentry/core/SystemOutLogger.java
Log stacktraces in SystemOutLogger when exception occurs.
With `debug` mode on, when exception happens it's currently difficult to find out why and where did it happen. With stacktraces printed to the console we can easily find the bug.
> Log stacktraces in SystemOutLogger

- sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
Ideally we wouldn't have this public since it's not expected that users define the value they want for this.
We should add `sentry.java/version` by default in the core package, and override it if an outer package is wrapping it (i.e android).
But I'd just leave it out of the sample.
> ref: Remove explicit client name from sample

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/main/java/io/sentry/core/DateUtils.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-core/src/main/java/io/sentry/core/SessionAdapter.java
- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
- sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
fix: converting UTC and ISO timestamp if missing Locale or time zones.
Andromax G36C1H
Smartfren Andromax AD6B1H
Andromax C46B2H
devices have problems with getting US locale or UTC/GTM time zones.
I can't really test it, I don't have those devices or found emulators.
> fix: converting UTC and ISO timestamp when missing Locale/TimeZone do not error

- buildSrc/src/main/java/Config.kt
- sentry-android-core/build.gradle.kts
- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidOptionsTest.kt
- sentry-android-ndk/src/test/java/io/sentry/android/ndk/SentryNdkUtilTest.kt
- sentry-core/build.gradle.kts
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/test/java/io/sentry/core/SentryOptionsTest.kt
Sets `SdkVersion` in `SentryOptions` created in sentry-core module from build-time generated class `BuildConfig`.
https://github.com/getsentry/sentry-java/issues/873
> Set `SdkVersion` in default `SentryOptions` created in sentry-core module

- sentry-core/src/main/java/io/sentry/core/EventProcessor.java
- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
Null return is used when the event should be dropped. This aligns with the current handling in `sentry-android` code and also with the Sentry unified API definition of event processors.
Alignment with unified API https://develop.sentry.dev/sdk/unified-api/#terminology
> make EventProcessor.process Nullable

- sentry-core/src/test/java/io/sentry/core/SentryTest.kt
Add tests for verifying scope changes thread isolation
https://github.com/getsentry/sentry-java/issues/885
> Add tests for verifying scope changes thread isolation

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
- sentry-core/src/test/java/io/sentry/core/MainEventProcessorTest.kt
SDK version should be set outside of Android specific configuration so that it's taken into account for plain `sentry-java` usage as well as other non-android integrations.
When developing Logback integration (#511) I found out that SDK version is not set on `SentryEvent` even if it's set on `SentryOptions`.
"unit tests are green" but I haven't done any real Android device tests.
Once merged, pull these changes into `feature/sentry-java` branch so that [one test](https://github.com/getsentry/sentry-android/pull/511/files#diff-2a3d6f2986d090a3e4bfa63a870752d3R137) in Logback integration can be un-ignored
> Set SDK version in `MainEventProcessor`.

- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/test/java/io/sentry/core/SentryTest.kt
Logs a warning if SDK is initialized more than once - which can happen if user uses two integrations (for example Logback and Spring Boot) but tries to configure both of them. 
Problem discussed in https://github.com/getsentry/sentry-android/pull/511#discussion_r472287885
> Warn about Sentry re-initialization.

- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-samples/sentry-samples-spring-boot/src/main/java/io/sentry/samples/spring/SecurityConfiguration.java
- sentry-samples/sentry-samples-spring-boot/src/main/resources/application.properties
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryRequestFilter.java
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryRequestHttpServletRequestProcessor.java
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentrySecurityFilter.java
- sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryUserHttpServletRequestProcessor.java
- sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryRequestHttpServletRequestProcessorTest.kt
- sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentrySpringIntegrationTest.kt
- sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryUserHttpServletRequestProcessorTest.kt
Add `sendDefaultPii` flag to `SentryOptions`.
Filters out user information and sensitive request headers in Spring Boot integration if this flag is set to false.
Discussion initially started when working on Spring Boot integration - we want to give users option to decide if detailed user information is sent or not - similar to how it's done in Python integration: https://docs.sentry.io/error-reporting/configuration/?platform=python
Supersedes #527.
> Add `sendDefaultPii` flag to `SentryOptions`.

- sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java
- sentry-logback/src/test/kotlin/io/sentry/logback/SentryAppenderTest.kt
- sentry-samples/sentry-samples-logback/src/main/resources/logback.xml
Logback integration gets now an option to set `minimumEventLevel` and `minimumBreadcrumbLevel`. Breadcrumbs are attached to current scope and sent along with following `SentryEvent`.
Requested by @bruno-garcia.
> Attach breadcrumbs to events triggered in Logback integration.

- sentry-samples/sentry-samples-android/build.gradle.kts
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
fix: enable session sample
session tracking was disabled on android sample, i made it by mistake while testing things
added a conditional sentryEnvironment for free
> fix: enable session sample

- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/SentryThreadFactory.java
- sentry-core/src/test/java/io/sentry/core/SentryThreadFactoryTest.kt
`isAttachStacktrace` was passed down in `SentryOptions` constructor before this field was initialized with setters.
This PR changes it in a way that instead of raw value, instances of `SentryOptions` is passed down which also enables potential reconfiguring of this flag during runtime.
There was a bug we found out while working on Spring integration.
> Fix resolving isAttachStacktrace flag.

- buildSrc/src/main/java/Config.kt
- sentry-android-core/build.gradle.kts
- sentry-android-core/src/test/java/io/sentry/android/core/ANRWatchDogTest.kt
- sentry-android-ndk/build.gradle.kts
- sentry-android-timber/build.gradle.kts
- sentry-android-timber/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- sentry-core/build.gradle.kts
- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/SentryThreadFactory.java
- sentry-core/src/test/java/io/sentry/core/DirectoryProcessorTest.kt
- sentry-core/src/test/java/io/sentry/core/EnvelopeSenderTest.kt
- sentry-core/src/test/java/io/sentry/core/SendCachedEventTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryExceptionFactoryTest.kt
- sentry-core/src/test/java/io/sentry/core/UncaughtExceptionHandlerIntegrationTest.kt
- sentry-core/src/test/java/io/sentry/core/util/Extensions.kt
Bump: test libs and plugins
keeping test libs and plugins up to date
edit: Upgrade Kotlin to 1.4.0 and robolectric to 4.4, they have breaking changes so it'd take more time to fix, as they are only for testing, I won't do it now. -> done
replace `@TestOnly` with more specific `@VisibleForTesting`
> Bump: test libs and plugins
