- sentry-core/src/main/java/io/sentry/Scope.java
- sentry-core/src/main/java/io/sentry/SentryEvent.java
- sentry-core/src/main/java/io/sentry/SentryLevel.java
- sentry-core/src/main/java/io/sentry/protocol/SdkVersion.java
removed not used attributes from Scope and removed the inheritance from SentryEvent and duplicated needed events
> fixed Scope and SentryEvent attributes

- build.gradle.kts
This is mixed up with the Gson PR but it's a pain so let's just add this before we figure out Gson
> ref: Run spotless on build

- sentry-android/build.gradle.kts
- sentry-core/src/main/java/io/sentry/DateUtils.java
> set lint to check its dependencies as well

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidSerializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/DateDeserializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/DateSerializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryIdDeserializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/SentryIdSerializerAdapter.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidSerializerTest.kt
If parsing json using our custom gson adapters, App. might crash and we won't know why.
We wanna know if there were errors while parsing jsons using custom gson adapters
There are unit tests for custom gson adapters already
> logging errors on Gson adapters

- sentry-android-core/build.gradle.kts
- sentry-android-core/src/main/AndroidManifest.xml
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidSerializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/DateDeserializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/DateSerializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/OrientationDeserializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/OrientationSerializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/SentryIdDeserializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/SentryIdSerializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/TImeZoneDeserializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/TimeZoneSerializerAdapter.java
- sentry-android-core/src/main/java/io/sentry/android/core/util/Permissions.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidSerializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryInitProviderTest.kt
- sentry-core/src/main/java/io/sentry/core/DiagnosticLogger.java
- sentry-core/src/main/java/io/sentry/core/Dsn.java
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/protocol/App.java
- sentry-core/src/main/java/io/sentry/core/protocol/Contexts.java
- sentry-core/src/main/java/io/sentry/core/protocol/Device.java
- sentry-core/src/main/java/io/sentry/core/protocol/OperatingSystem.java
- sentry-core/src/main/java/io/sentry/core/protocol/Runtime.java
- sentry-core/src/main/java/io/sentry/core/util/Objects.java
- sentry-sample/build.gradle.kts
> Device context

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
executing spotlessApply manually
for some reason, spotlessApply failed when PR was merged
> spotlessApply

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/main/java/io/sentry/core/SystemOutLogger.java
renaming sdk_version to sdk and fixing SystemOutLogger
sdk name is and SystemOutLogger format is wrong
> minor fixes

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidSerializer.java
- sentry-core/src/main/java/io/sentry/core/AsyncConnectionFactory.java
- sentry-core/src/main/java/io/sentry/core/CredentialsSettingConfigurator.java
- sentry-core/src/main/java/io/sentry/core/EnvelopeReader.java
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/main/java/io/sentry/core/transport/RetryingThreadPoolExecutor.java
- sentry-core/src/main/java/io/sentry/core/transport/TransportResult.java
- sentry-core/src/test/java/io/sentry/core/transport/HttpTransportTest.kt
* DSN has to be parsed and Sentry URL built
* Timeouts are in millseconds
> fix: Fixes for the HTTP transport

- sentry-core/src/main/java/io/sentry/core/EnvelopeReader.java
@marandaneto AS showed you the warning while Intellij didn't show me.
I guess I need to change IDEs
> ref: remove redundant condition

- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/main/java/io/sentry/core/SentryThreadFactory.java
- sentry-core/src/main/java/io/sentry/core/SentryValues.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryStackFrame.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryStackTrace.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryThread.java
- sentry-core/src/test/java/io/sentry/core/SentryThreadFactoryTest.kt
@marandaneto I realize the stackframe code is duplicated with another open PR.
I suggest we merge both and create another one for refactoring. What do you say?
> feat: Threads

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java
- sentry-android-ndk/src/main/jni/sentry.c
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
This writes envelopes to the cache folder now.
> feat: initial NDK transport via file system

- sentry-android-core/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android-ndk/proguard-rules.pro
- sentry-android/build.gradle.kts
just refactoring the NDK gradle file and adding the proguard file.
NDK gradle file was a bit messy and not kotlin friendly
> setting up tests env. for NDK module and adding proguard file to NDK

- sentry-android-core/proguard-rules.pro
> fix r8 gson warning

- sentry-sample/CMakeLists.txt
- sentry-sample/build.gradle.kts
- sentry-sample/src/main/cpp/native-sample.cpp
- sentry-sample/src/main/java/io/sentry/sample/MainActivity.java
- sentry-sample/src/main/java/io/sentry/sample/NativeSample.java
- sentry-sample/src/main/res/layout/activity_main.xml
Button to raise a sigsegv to help us test the signal handler integration with NDK
> feat: Sample raises sigsegv

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
getting device name
device name was not available.
> getting device name

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- sentry-android-core/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-core/build.gradle.kts
- sentry-sample/build.gradle.kts
bump to gradle 5.6.4
gradle 5.6.3 has an issue with kotlinOptions.
> bump to gradle 5.6.4

- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
added try block to before callbacks and logged if an error has occurred
currently, if an error happens on before callbacks, App. may crash.
> added try block to before callbacks and logged if an error has occurred

- sentry-core/src/test/java/io/sentry/core/transport/RetryingThreadPoolExecutorTest.kt
@marandaneto pointed out the closed PR had a fix we should bring in
> fix: Fix racey test

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidLogger.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/main/java/io/sentry/core/CircularFifoQueue.java
- sentry-core/src/main/java/io/sentry/core/DateUtils.java
- sentry-core/src/main/java/io/sentry/core/Dsn.java
- sentry-core/src/main/java/io/sentry/core/EnvelopeReader.java
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/IHub.java
- sentry-core/src/main/java/io/sentry/core/InvalidDsnException.java
- sentry-core/src/main/java/io/sentry/core/NoOpLogger.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelope.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeHeader.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeItem.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeItemHeader.java
- sentry-core/src/main/java/io/sentry/core/SentryValues.java
- sentry-core/src/main/java/io/sentry/core/SynchronizedCollection.java
- sentry-core/src/main/java/io/sentry/core/SynchronizedQueue.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/main/java/io/sentry/core/protocol/Contexts.java
fixed warnings detected by linting
> fixed warnings detected by linting

- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/main/java/io/sentry/core/IHub.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/protocol/User.java
- sentry-core/src/test/java/io/sentry/core/BreadcrumbTest.kt
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/ScopeTest.kt
- sentry-core/src/test/java/io/sentry/core/protocol/UserTest.kt
copy by Serialization is too slow:
https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/SerializationUtils.java
Scope should clone its fields
> deep-copy to scope and its fields

- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroid.java
- sentry-core/src/main/java/io/sentry/core/OptionsContainer.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
added class container for SentryOptions
it's common in Android that you have a container for it.
> added class container for SentryOptions

- sentry-android-core/src/main/java/io/sentry/android/core/EnvelopeFileObserverIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/EnvelopeFileObserverIntegrationTest.kt
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandler.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/test/java/io/sentry/core/UncaughtExceptionHandlerIntegrationTest.kt
closing integrations, so it won't leak file observers or handlers
integrations were leaking observers and/or handlers
> closing integrations, so it wont leak observers or handlers

- buildSrc/src/main/java/Config.kt
- sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java
- sentry-android-ndk/build.gradle.kts
- sentry-sample/build.gradle.kts
- sentry-sample/src/main/AndroidManifest.xml
- sentry-sample/src/main/res/layout/activity_main.xml
- sentry-sample/src/main/res/values/strings.xml
BUMP AGP and small lint issues
using last AGP, using minSdkVersion=14 and fixing small issues
> bump AGP and small fixes

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidSerializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/UnknownPropertiesTypeAdapterFactory.java
- sentry-android-core/src/main/java/io/sentry/android/core/adapters/ContextsDeserializerAdapter.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidSerializerTest.kt
- sentry-core/src/main/java/io/sentry/core/protocol/App.java
- sentry-core/src/main/java/io/sentry/core/protocol/Browser.java
- sentry-core/src/main/java/io/sentry/core/protocol/Device.java
- sentry-core/src/main/java/io/sentry/core/protocol/Gpu.java
- sentry-core/src/main/java/io/sentry/core/protocol/OperatingSystem.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryRuntime.java
created a gson adapter for Contexts
Cotnexts were deserialized as LinkedTreeMap
fixed unit tests TODOs
> created an adapter for Contexts

- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-sample/src/main/AndroidManifest.xml
renaming io.sentry.ndk to io.sentry.ndk.enable
semantically better
> renaming io.sentry.ndk to io.sentry.ndk.enable

- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryStackTraceFactory.java
- sentry-core/src/main/java/io/sentry/core/SentryThreadFactory.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/main/java/io/sentry/core/protocol/Gpu.java
- sentry-core/src/main/java/io/sentry/core/protocol/Mechanism.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryStackFrame.java
- sentry-core/src/main/java/io/sentry/core/protocol/SentryThread.java
- sentry-core/src/main/java/io/sentry/core/transport/CrashedEventStore.java
- sentry-core/src/test/java/io/sentry/core/MainEventProcessorTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryExceptionFactoryTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryStackTraceFactoryTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryThreadFactoryTest.kt
- sentry-core/src/test/java/io/sentry/core/UncaughtExceptionHandlerIntegrationTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/CrashedEventStoreTest.kt
- sentry-sample/src/main/AndroidManifest.xml
- sentry-sample/src/main/java/io/sentry/sample/MainActivity.java
added errored field and fixes
we need an `errored` to mark as the current thread but necessarily crashed.
stacktraces were out of order.
> added errored field and fixes

- buildSrc/src/main/java/Config.kt
- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/main/java/io/sentry/core/Hub.java
bumping libs
eg Robolectric 4.3.1 adds support for Android API 29 (Q final).
> bump 3rd party libs

- sentry-sample/build.gradle.kts
enable app. shriking
to guarantee that the lib. works correctly with shrinking as well.
> enable app. shriking

- sentry-android-core/proguard-rules.pro
Automatically include a rule to avoid minification of exceptions
See https://github.com/getsentry/sentry-java/issues/711#issuecomment-550443950
> feat: Don't minify exception types

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/EnvelopeFileObserverIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/EnvelopeFileObserverIntegrationTest.kt
We'll attempt to send it, if it fails, we'll send on app-restart only at this point.
> ref: Don't observe events from java

- sentry-core/src/main/java/io/sentry/core/ISentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
It still doesn't write the envelope header event_id but it write message
> ref: event message back

- sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java
- sentry-sample/src/main/AndroidManifest.xml
- sentry-sample/src/main/java/io/sentry/sample/MainActivity.java
Fire it in a shorter interval and block for a bit longer to fire every time
> ref: Sample ANR

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
fix external storage check
external storage check is wrong (it's the same as internal storage) due to different implementations of all Android SDK versions.
using real devices and emulator, also with a real sdcard.
> fix external storage size

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java
adding dalvik package to in app exclude
dalvik package was being considered in app.
> adding dalvik package to in app exclude

- sentry-core/src/main/java/io/sentry/core/MainEventProcessor.java
don't apply current threads to cached events
It doesn't make much sense to get current threads and stack traces if an event was cached.
> don't apply current threads to cached events

- buildSrc/src/main/java/Config.kt
- sentry-android-core/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-core/build.gradle.kts
removing custom pom as its not adding dependencies, fix will follow soon
published artifacts were not getting its dependencies
built locally and checked final pom
fix the pom generation
> removing custom pom generation

- buildSrc/src/main/java/Config.kt
BUMP kotlin and leakcanary
there's a new version of Kotlin and Leakcanary
> BUMP kotlin and leakcanary

- buildSrc/src/main/java/Config.kt
> bump novoda-bintray plugin

- sentry-android-core/proguard-rules.pro
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidOptionsInitializerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/EnvelopeFileObserverIntegrationTest.kt
- sentry-core/src/main/java/io/sentry/core/NoOpSerializer.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/test/java/io/sentry/core/DiagnosticLoggerTest.kt
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/NoOpSerializerTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryOptionsTest.kt
- sentry-core/src/test/java/io/sentry/core/UncaughtExceptionHandlerIntegrationTest.kt
- sentry-core/src/test/java/io/sentry/core/cache/DiskCacheTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/HttpTransportTest.kt
added annotations to options and no-op to serializer
better experience to the user when setting options up.
unit tests
release alpha09
> added annotations to options and no-op to serializer

- buildSrc/src/main/java/Config.kt
- sentry-android-core/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-core/build.gradle.kts
change publish overriding to false, so if you try to publish a version that already exists, it won't allow you.
also removing dryRun as it's already the default value.
just preventing us to make mistakes.
> change publish overriding to false

- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
timestamps are package private or testonly.
timestamps should be generated only by ctor.
compiling the project.
> timestamps should be internal and generated by ctor

- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/test/java/io/sentry/core/BreadcrumbTest.kt
added ctor overload for breadcrumb message.
too much boilerplate for a simple string.
> added ctor overload for breadcrumb message

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/EnvelopeSender.java
using try with resources as its desugared.
just to use features of java8 when possible.
> using try with resources as its desugared

- README.md
added blog posts to README.
Because it's nice and it shows how to report breadcrumbs automatically for example.
> added blog posts to README

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransportGate.java
- sentry-android-core/src/main/java/io/sentry/android/core/Installation.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidTransportGateTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ConnectivityCheckerTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/DefaultAndroidEventProcessorTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/InstallationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/NdkIntegrationTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/PermissionsTest.kt
- sentry-android-core/src/test/java/io/sentry/android/core/SentryAndroidTest.kt
- sentry-core/src/main/java/io/sentry/core/DiagnosticLogger.java
- sentry-core/src/test/java/io/sentry/core/OptionsContainerTest.kt
added some unit tests
trying to add some unit tests more, our coverage is not great yet, but some classes are hard to test due framework or static access.
> added some unit tests

- sentry-android-ndk/build.gradle.kts
update to the latest stable ndk.
builds/CI are broken.
build locally and CI.
> update to the latest stable ndk

- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-core/src/test/java/io/sentry/core/ScopeTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
remove stack trace of breadcrumb errors.
stack trace may be minified and it could give a bad user experience.
> remove stack trace of breadcrumb errors

- sentry-android-ndk/build.gradle.kts
- sentry-core/src/main/java/io/sentry/core/IHub.java
- sentry-core/src/main/java/io/sentry/core/ISentryClient.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
fix lgtm build because of new ndk version.
lgtm build is broken.
this CI.
> fix lgtm build because of new ndk version

- sentry-core/src/test/java/io/sentry/core/EnvelopeSenderTest.kt
refactored unit test for non null logger.
unit test.
> refactored unit test for non null logger

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
removed unnecessary check on the logger.
DiagnosticLogger already does it.
> removed unnecessary check on logger

- sentry-sample/build.gradle.kts
fix if symlink exists for sentry-native.
right now symlink existance for sentry-sample is wrong.
printing and building it.
> fix if symlink exists for sentry-native

- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/IHub.java
- sentry-core/src/main/java/io/sentry/core/NoOpHub.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
added remove methods (tags/extras) to the sentry static class.
I've added them to the scope class, but I've forgotten to add to the sentry static class.
> added remove methods (tags/extras) to the sentry static class

- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
release now is health compat:
package@versionName+versionCode
eg: io.sentry.test@1.0.0+202001211 
We want to send the new release format to be compatible with Health.
debugging it, constants are code generated, not worth to mock it.
> new Release format

- buildSrc/src/main/java/Config.kt
BUMP build-tools
because I like to keep up to date.
Fixes a Catalina issue.
CI is gonna test for me.
> BUMP build-tools

- sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/EnvelopeFileObserverIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/NdkIntegration.java
- sentry-core/src/main/java/io/sentry/core/SendCachedEventFireAndForgetIntegration.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/test/java/io/sentry/core/SendCachedEventFireAndForgetIntegrationTest.kt
adding logs to installed integrations.
It would be good to know which integrations have been installed or why not.
build and logcat.
> adding logs to installed integrations

- MIGRATION.md
- README.md
README 2.0, moving away from beta description.
Android is GA, yey.
> README 2.0

- build.gradle.kts
- sentry-native-sample/build.gradle.kts
remove maven local from build scripts.
better to avoid broken builds made locally.
building it.
> remove maven local from build scripts

- sentry-core/src/main/java/io/sentry/core/transport/RetryingThreadPoolExecutor.java
- sentry-core/src/test/java/io/sentry/core/transport/RetryingThreadPoolExecutorTest.kt
fix flaky test
test is flaky when delay is very low, like 50ms
unit test and CI passing on parallel mode
> fix flaky test

- .appveyor.yml
- .travis.yml
- build.gradle.kts
- buildSrc/src/main/java/Config.kt
- gradle.properties
- sentry-android-core/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-core/build.gradle.kts
Support mavenCentral sync.
Right now we don't publish on mavenCentral and we'd like to do it.
deploying on mavenLocal.
break and reuse build files, already have a task for that.
> Support mavenCentral sync

- build.gradle.kts
- buildSrc/src/main/java/Config.kt
- gradle/wrapper/gradle-wrapper.properties
- sentry-android-core/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-core/build.gradle.kts
Fix bintray/maven central sync.
> Fix bintray/maven central sync

- buildSrc/src/main/java/Config.kt
bump bintray plugin 1.0.1
v1.0.0 was not adding name, desc, and url to generated pom.
deployed locally and checked pom content.
> bump bintray plugin 1.0.1

- .appveyor.yml
- .travis.yml
- buildSrc/src/main/java/Config.kt
BUMP AGP to 3.6.1
AGP 3.6.x has build speed improvements
Building and running it
> BUMP AGP to 3.6.1

- buildSrc/src/main/java/Config.kt
bump kotlin to 1.3.70.
better kotlin/gradle DSL support.
> bump kotlin to 1.3.70

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidSerializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/ManifestMetadataReader.java
- sentry-android-ndk/src/main/java/io/sentry/android/ndk/SentryNdk.java
- sentry-core/src/main/java/io/sentry/core/AsyncConnectionFactory.java
- sentry-core/src/main/java/io/sentry/core/EnvelopeSender.java
- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/ISentryClient.java
- sentry-core/src/main/java/io/sentry/core/ISerializer.java
- sentry-core/src/main/java/io/sentry/core/NoOpSentryClient.java
- sentry-core/src/main/java/io/sentry/core/NoOpSerializer.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelope.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeHeader.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeItem.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeItemHeader.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-core/src/main/java/io/sentry/core/SessionAdapter.java
- sentry-core/src/main/java/io/sentry/core/cache/EnvelopeCache.java
- sentry-core/src/main/java/io/sentry/core/cache/IEnvelopeCache.java
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/main/java/io/sentry/core/transport/NoOpEnvelopeCache.java
- sentry-core/src/test/java/io/sentry/core/transport/AsyncConnectionTest.kt
- sentry-sample/src/main/AndroidManifest.xml
> Doing open TODOs for session envelopes

- sentry-core/src/main/java/io/sentry/core/transport/TransportResult.java
make transport result public
one could extend `ITransport` and make a stdout transport for example.
> make transport result public

- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeItem.java
- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-core/src/main/java/io/sentry/core/UncaughtExceptionHandlerIntegration.java
- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/test/java/io/sentry/core/EnvelopeSenderTest.kt
- sentry-core/src/test/java/io/sentry/core/HubTest.kt
- sentry-native-sample/build.gradle.kts
> no network flush on session update, only on start and end

- sentry-android-core/src/test/java/io/sentry/android/core/LifecycleWatcherTest.kt
- sentry-core/src/main/java/io/sentry/core/SendCachedEvent.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/cache/DiskCache.java
- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
> current session as a json and not an envelope

- sentry-android-core/src/test/java/io/sentry/android/core/AndroidSerializerTest.kt
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-core/src/main/java/io/sentry/core/SessionAdapter.java
- sentry-core/src/test/java/io/sentry/core/EnvelopeSenderTest.kt
- sentry-core/src/test/java/io/sentry/core/ScopeTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryEnvelopeItemTest.kt
- sentry-core/src/test/java/io/sentry/core/SessionTest.kt
- sentry-core/src/test/java/io/sentry/core/cache/SessionCacheTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/AsyncConnectionTest.kt
- sentry-core/src/test/java/io/sentry/core/transport/HttpTransportTest.kt
session has a ctor
so we don't deal with racey fields
already has unit tests
> session has a ctor with params

- buildSrc/src/main/java/Config.kt
- gradle/wrapper/gradle-wrapper.properties
BUMP gradle and kotlin
so we know it's not breaking anything.
CI/unit tests are happy
> BUMP gradle and kotlin

- sentry-core/src/main/java/io/sentry/core/SentryClient.java
update session data fix
we need to that after processors or exceptions won't be there to check if event is crashed or errored.
executing it and it already has unit tests.
> update session data fix

- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/test/java/io/sentry/core/SentryEventTest.kt
NPE check so handled flag won't blow up an exception
as handled is not a primitive type, we need to NPE check.
> NPE check so handled flag won't blow up an exception

- build.gradle.kts
- buildSrc/src/main/java/Config.kt
- gradle.properties
- sentry-android-core/build.gradle.kts
- sentry-android-ndk/build.gradle.kts
- sentry-android/build.gradle.kts
setting release data on a properties file
it's just easier than opening Config.kt and also easier to parse on Craft
> setting release data on a properties file

- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
- sentry-core/src/test/java/io/sentry/core/cache/SessionCacheTest.kt
- sentry-sample/build.gradle.kts
- sentry-sample/src/main/AndroidManifest.xml
update current session file on hardcrash
session was being updated as an envelope instead of a session json file
> update current session file on hardcrash

- buildSrc/src/main/java/Config.kt
> bump bintray-release

- sentry-sample/src/main/AndroidManifest.xml
Manifest describes all its configurations
you would be able to know all its configurations by following the sample
> Manifest describes all its configurations

- buildSrc/src/main/java/Config.kt
> bump agp to 3.6.2

- MIGRATION.md
add a capture event example to MIGRATION.md
this example was missing on our migration guideline
> add a capture event example to MIGRATION.md

- buildSrc/src/main/java/Config.kt
> bump bintray-release 1.0.3

- .appveyor.yml
- .travis.yml
- Makefile
- sentry-android-core/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-core/build.gradle.kts
create a make file
while we don't have craft, this helps us out.
> create a make file

- buildSrc/src/main/java/Config.kt
> BUMP kotlin plugin

- README.md
Update README.md with examples section
getsentry/examples is helpful and should be visible here too.
> Update README.md with examples section

- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
> bump sentry-native to 0.2.4

- Makefile
- buildSrc/src/main/java/Config.kt
bump AGP and add new make cmd to check for updates
I've always needed to check versions manually.
the latest AGP has bug fixes.
> bump AGP and add new make cmd to check for updates

- .appveyor.yml
- .travis.yml
bump NDK to 21.0.6113669
latest stable NDK version is 21.0.6113669
CI is happy
> bump NDK to 21.0.6113669

- sentry-core/src/main/java/io/sentry/core/Hub.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
make capture session and envelope internal
they are for internal reasons, not a public API.
> make capture session and envelope internal

- sentry-core/src/test/java/io/sentry/core/SentryExceptionFactoryTest.kt
added test for anonymous exception
inspiration of getsentry/sentry-java/pull/834
> added a test for anonymous exception

- sentry-core/src/main/java/io/sentry/core/transport/AsyncConnection.java
- sentry-core/src/test/java/io/sentry/core/transport/AsyncConnectionTest.kt
discard events and envelopes if cached and retry after
events and envelopes were not discarded if they were cached and retry after
> discard events and envelopes if cached and retry after

- sentry-sample/src/main/AndroidManifest.xml
add samples of how to disable automatic breadcrumbs
it's easier to see than reading the code.
> add samples of how to disable automatic breadcrumbs

- sentry-android-core/src/main/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegration.java
- sentry-android-core/src/test/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegrationTest.kt
add trim memory breadcrumbs
newer versions only implement trim memory and not both.
running and unit test
> enha: add trim memory breadcrumbs

- buildSrc/src/main/java/Config.kt
bump leakcanary on sample app
leakcanary has fixes and improvements
> bump leakcanary on sample app

- sentry-android-core/src/main/java/io/sentry/android/core/AndroidSerializer.java
- sentry-core/src/main/java/io/sentry/core/SentryClient.java
- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-core/src/main/java/io/sentry/core/SessionAdapter.java
- sentry-core/src/main/java/io/sentry/core/cache/SessionCache.java
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
sessions cant be abnormal, but exited if not ended properly
abnornal sessions for mobile doesn't make sense.
> fix: sessions cant be abnormal, but exited if not ended properly

- sentry-core/src/main/java/io/sentry/core/HttpTransportFactory.java
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
added options to configure http transport
one might want custom values for read/connection http headers.
also one may ignore TLS errors.
> added options to configure http transport

- .appveyor.yml
- gradle/wrapper/gradle-wrapper.properties
Bump to Gradle 6.4.1
gradle/gradle/issues/13157
> Bump Gradle to 6.4.1

- sentry-android-core/src/main/java/io/sentry/android/core/util/RootChecker.java
fix: do not log root checker error if this is the expected behavior
only log an `error` message if it's indeed something unexpected, in this case, if `su` doesn't exist, only log a `debug` message.
tests already exist.
> fix: do not log root checker error if this is the expected behavior

- sentry-core/src/test/java/io/sentry/core/DsnTest.kt
test: adding a test for DSN with query strings, they should be ignored
> test: adding a test for DSN with query strings, they should be ignored

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Bump Gradle to 6.5

- README.md
> doc: List min API

- sentry-core/src/test/java/io/sentry/core/transport/QueuedThreadPoolExecutorTest.kt
adding a comment for a flaky test when running thru AS/project tool context
> doc: add a comment for flaky test through AS project tool context

- sentry-core/src/test/java/io/sentry/core/transport/StdoutTransportTest.kt
> fix: typo junit import

- build.gradle.kts
- buildSrc/src/main/java/Config.kt
- gradle.properties
- sentry-android-core/build.gradle.kts
- sentry-android-core/src/main/java/io/sentry/android/core/AndroidSerializer.java
- sentry-android-core/src/main/java/io/sentry/android/core/AppComponentsBreadcrumbsIntegration.java
- sentry-android-core/src/main/java/io/sentry/android/core/DefaultAndroidEventProcessor.java
- sentry-android-core/src/main/java/io/sentry/android/core/util/RootChecker.java
- sentry-android-ndk/build.gradle.kts
- sentry-android/build.gradle.kts
- sentry-core/src/main/java/io/sentry/core/Breadcrumb.java
- sentry-core/src/main/java/io/sentry/core/CircularFifoQueue.java
- sentry-core/src/main/java/io/sentry/core/DateUtils.java
- sentry-core/src/main/java/io/sentry/core/Scope.java
- sentry-core/src/main/java/io/sentry/core/Sentry.java
- sentry-core/src/main/java/io/sentry/core/SentryEnvelopeItemHeaderAdapter.java
- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/main/java/io/sentry/core/Session.java
- sentry-core/src/main/java/io/sentry/core/SynchronizedQueue.java
- sentry-core/src/main/java/io/sentry/core/protocol/App.java
- sentry-core/src/main/java/io/sentry/core/protocol/Device.java
- sentry-core/src/main/java/io/sentry/core/protocol/Message.java
- sentry-core/src/main/java/io/sentry/core/protocol/User.java
- sentry-core/src/main/java/io/sentry/core/transport/HttpTransport.java
- sentry-core/src/main/java/io/sentry/core/transport/ITransportGate.java
- sentry-core/src/test/java/io/sentry/core/transport/StdoutTransportTest.kt
- sentry-sample/build.gradle.kts
enhancement: Bump static code analyses and fix its issues
add missing javadocs, suppress issues, comment on empty catch blocks etc
> enhancement: Bump static code analyses and fix its issues

- sentry-android-core/src/main/java/io/sentry/android/core/adapters/ContextsDeserializerAdapter.java
- sentry-android-core/src/test/java/io/sentry/android/core/AndroidSerializerTest.kt
- sentry-android-core/src/test/resources/event_with_contexts.json
fix: deserialise unmapped contexts values from envelope
contexts fields were missing from a react native event
unit tests
> fix: deserialise unmapped contexts values from envelope

- gradle/wrapper/gradle-wrapper.properties
Bump Gradle 6.5.1
6.5.1 has fixed caching issues
> enhancement: Bump Gradle 6.5.1

- buildSrc/src/main/java/Config.kt
Bump: AGP 4.0.1
for Android 11 features
> Bump: AGP 4.0.1

- buildSrc/src/main/java/Config.kt
Bump plugin versions
upgrade plugin versions
> Bump plugin versions

- sentry-core/src/main/java/io/sentry/core/SentryEvent.java
- sentry-core/src/test/java/io/sentry/core/SentryEventTest.kt
Add method to add breadcrumb with string parameter.
The same as #500 but against master.
See https://github.com/getsentry/sentry-android/pull/499#discussion_r462614172
There's a unit test.
> Add method to add breadcrumb with string parameter.

- sentry-samples/sentry-samples-console/build.gradle.kts
- sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
- settings.gradle.kts
Added console application sample. Code is a direct translation from console sample in `sentry-dotnet` repository excluding features that are not implemented in `sentry-java`.
Sample console application is a living documentation and guides users through Java SDK features.
Same as #499 with all code review comments addressed, just against `master`.
> Add console application sample.

- buildSrc/src/main/java/Config.kt
- gradle/wrapper/gradle-wrapper.properties
- sentry-core/src/test/java/io/sentry/core/DiagnosticLoggerTest.kt
- sentry-core/src/test/java/io/sentry/core/SendCachedEventFireAndForgetIntegrationTest.kt
- sentry-core/src/test/java/io/sentry/core/SentryClientTest.kt
- sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java
Bump Gradle to 6.6 and fix linting issues
Build improvements
CI is happy
> Bump Gradle to 6.6 and fix linting issues

- sentry-android-ndk/src/main/jni/sentry.c
Bump sentry-native to 0.4.0
keeping sentry-native up to date
> Bump sentry-native to 0.4.0

- gradle.properties
Bump SDK to 3.0.0-alpha.1
Because of refactoring, breaking changes etc we need to Bump a major version to align with sentry-java
> Bump SDK to 3.0.0-alpha.1

- sentry-android-core/src/test/java/io/sentry/android/core/ManifestMetadataReaderTest.kt
- sentry-core/src/main/java/io/sentry/core/SentryOptions.java
- sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml
feat: enable release health by default
we'd like to enable release health for all the users unless they opt-out
> feat: enable release health by default

- buildSrc/src/main/java/Config.kt
- sentry-core/build.gradle.kts
- sentry-log4j2/build.gradle.kts
- sentry-logback/build.gradle.kts
- sentry-spring-boot-starter/build.gradle.kts
Move minimum required coverage to `Config` class and use same value (`0.6`) in all modules.
Reduce duplication and possibility of having different quality gates in different modules.
> Extract minimum required coverage by Jacoco plugin.
